#! /usr/bin/bash

home="/home/loki/"

dte(){
  dte="$(date +"%Y-%m-%d %H:%M")"
  echo -e "$dte"
}

mem(){
  mem=`free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
  echo -e "$mem"
}

bat(){
    bat="$($home/.scripts/batterystatus.sh)"
    echo -e "$bat"
}

bri(){
    bri="$($home/.scripts/get_brightness.sh)"
    echo -e "$bri"
}

vol(){
    echo -e "墳 $(pamixer --get-volume-human)"
}

cpu(){
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e "$cpu% cpu"
}

while true; do 
	xsetroot -name "$(cpu) | $(mem) | $(bat) | $(vol) | $(bri) | $(dte)"
	sleep 10
done
