#! /usr/bin/bash

home="/home/loki/"
sep=" | "

#~~~~~~~~~~~~Date~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
dte(){
  dte="$(date +"%Y-%m-%d %H:%M")"
  echo -e "$dte"
}

#~~~~~~~~~~~~Memory~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
mem(){
  mem=`free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
  echo -e "$mem$sep"
}

#~~~~~~~~~~~~Battery~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
bat(){
    if [ "$(hostname)" == "bifrost" ]; then
	bat="$($home/.scripts/batterystatus.sh)"
	echo -e "$bat$sep"
    fi
}

#~~~~~~~~~~~~Brightness~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
bri(){
    if [ "$(hostname)" == "bifrost" ]; then
	bri="$($home/.scripts/get_brightness.sh)"
	echo -e "$bri$sep"
    fi
}

#~~~~~~~~~~~~Volume~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
vol(){
    echo -e " 墳 $(pamixer --get-volume-human)$sep"
}

#~~~~~~~~~~~~CPU~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
cpu(){
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e "$cpu% cpu$sep"
}

#~~~~~~~~~~~~Music~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
mus(){
    if [ "$(hostname)" == "walhall" ]; then
	music=$(echo $(mpc) | sed -e 's/\n//g' -e 's/\[playing\]/~/' -e 's/\[paused\]/~/' -e 's/~.*//g')
	echo " "$music$sep
    fi
}
#~~~~~~~~~~~~Network~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# 
# using https://linuxclues.blogspot.com/2009/11/shell-script-show-network-speed.html
net(){
    echo -en "$(cat $HOME/.cache/networktraffic | sed 's/\r//g')$sep"
}

temp(){
    [ "$(hostname)" == "walhall" ] && temp=$(sensors | grep "CPU Temperature" | awk '{print $3}' | sed 's/+//')
    [ "$(hostname)" == "bifrost" ] && temp=$(sensors | grep "Package id 0:" | awk '{print $4}' | sed 's/+//')
    echo "  "$temp$sep
}

status(){
    status="$(net)$(mus)$(bat)$(temp)$(vol)$(bri)$(dte)"
    echo "$status"
}

#~~~~~~~~~~~~Perform oneshot~~~~~~~~~~~~~~~~~~~~~~~~~~#
if [ $1 == "-oneshot" ]; then
    status="$(status)"
    echo $status
    exit
fi


#~~~~~~~~~~~~Loop this thing~~~~~~~~~~~~~~~~~~~~~~~~~~#
while true; do
    status="$(status)"
    echo  $status
    xsetroot -name "$status"
    sleep 2
done
